name:                bindings-ginac
version:             0.1.0.0
github:              "laserpants/bindings-ginac"
license:             GPL-2
author:              "laserpants"
maintainer:          "hildenjohannes@gmail.com"
copyright:           "2018 Johannes Hildén"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/laserpants/bindings-ginac#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  extra-libraries:
  - ginac
  - cln
  - stdc++
  c-sources: 
  - bindings_ginac.cpp
  - bindings_ginac.h
  cc-options: -fPIC --std=c++11 -O3 # -DDEBUG 
  ghc-options: -pgmlg++ -fPIC

executables:
  bindings-ginac-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bindings-ginac

tests:
  bindings-ginac-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bindings-ginac
